// <auto-generated />
using System;
using DP_Shop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DP_Shop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241226091656_UpdateUserTable")]
    partial class UpdateUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DP_Shop.Data.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 26, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9445),
                            Description = "Sản phẩm truyền thống",
                            Name = "Sản phẩm truyền thống"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 26, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9447),
                            Description = "Sản phẩm hiện đại",
                            Name = "Sản phẩm hiện đại"
                        });
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bánh Ép Huế Vị Thịt Nướng 40g",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734498100/chinh-300x300_tfdduo.png"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bánh Ép Huế Vị Thịt Nướng 40g",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734498099/Artboard-391-300x300_o3uacb.png"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bánh Ép Huế Gói Snack Vị Tép 40g",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734579317/2-300x300_rpepfq.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bánh Ép Huế Gói Snack Vị Tép 40g",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734579317/3_ciytdq.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bánh Ép Huế Gói Snack Vị Tép 40g",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734579318/Thiet-ke-chua-co-ten_w83xbi.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Bánh Ép Huế Gói Snack BBQ Vị Thịt Nướng 40g",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734579544/5-300x300_xkcm3z.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Bánh Ép Huế Gói Snack BBQ Vị Thịt Nướng 40g",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734579544/4-300x300_kkdq5f.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Bánh Ép Huế Gói Snack BBQ Vị Thịt Nướng 40g",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734579544/1-300x300_yn7thr.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Bánh Ép Huế Hải Sản Vị Tôm Thịt 65G",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734579658/Artboard-351-300x300_ceyyrk.png"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Bánh Ép Huế Hải Sản Vị Tôm Thịt 65G",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734579658/chinh-2-300x300_cf7cqt.png"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Bánh Ép Huế Hải Sản Vị Tôm Thịt 40G",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734579954/Artboard-361-300x300_ie5h9h.png"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Bánh Ép Huế Hải Sản Vị Tôm Thịt 40G",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734579954/chinh-3-300x300_j5x0wl.png"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Bánh ép Huế chay vị Sen Huế 65G",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734580057/Sen-768x576_mth6jv.png"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Bánh ép Huế chay vị Nấm Hương 65G",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734580131/9-300x300_rzn0md.jpg"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Bánh ép Huế chay vị Nấm Hương 65G",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734580132/12-300x300_mljbgd.jpg"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Bánh ép Huế chay vị Nấm Hương 65G",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734580133/Nam-1-300x300_vfz61t.png"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Bánh Ép Huế BBQ Vị Thịt Nướng 65G",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734580226/Artboard-391-300x300_jvirsd.png"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Bánh Ép Huế BBQ Vị Thịt Nướng 65G",
                            Url = "https://res.cloudinary.com/dlo5qxnxw/image/upload/v1734580226/chinh-300x300_yfjqj7.png"
                        });
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 12, 26, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9710),
                            Description = "Bánh ép Huế là một đặc sản khởi nguồn từ biển Thuận An, Huế. Bánh ép Huế là sản phẩm được chế biến theo công thức đặc biệt riêng, nhất là khi kết hợp hài hòa giữa thịt mỡ cùng với hương thơm của sả, hành, ớt, tạo nên vị ngon khó cưỡng, không thể tách rời. Bên cạnh đó, bánh có thể ăn kèm với tương ớt cay cay thì quá là ngon miệng. Bánh không chất bảo quản, không màu thực phẩm và được đóng gói trong hộp giấy đảm bảo chất lượng sản phẩm an toàn, khi được chứng nhận và cung cấp chứng chỉ an toàn vệ sinh thực phẩm HACCP.",
                            ExpiryDate = new DateTime(2025, 1, 25, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9711),
                            Name = "Bánh Ép Huế Vị Thịt Nướng 40g",
                            Price = 30000m,
                            Quantity = 50,
                            Slug = "banh-ep-hue-vi-thi-nuong-40g"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 12, 26, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9722),
                            Description = "Bánh ép Huế là một đặc sản khởi nguồn từ biển Thuận An, Huế. Bánh ép Huế là sản phẩm được chế biến theo công thức đặc biệt riêng, nhất là khi kết hợp hài hòa giữa thịt mỡ cùng với hương thơm của sả, hành, ớt, tạo nên vị ngon khó cưỡng, không thể tách rời. Bên cạnh đó, bánh có thể ăn kèm với tương ớt cay cay thì quá là ngon miệng. Bánh không chất bảo quản, không màu thực phẩm và được đóng gói trong hộp giấy đảm bảo chất lượng sản phẩm an toàn, khi được chứng nhận và cung cấp chứng chỉ an toàn vệ sinh thực phẩm HACCP.",
                            ExpiryDate = new DateTime(2025, 1, 25, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9723),
                            Name = "Bánh Ép Huế Gói Snack Vị Tép 40g",
                            Price = 35000m,
                            Quantity = 50,
                            Slug = "banh-ep-hue-goi-snack-vi-tep-40g"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 12, 26, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9726),
                            Description = "Bánh ép Huế là một đặc sản khởi nguồn từ biển Thuận An, Huế. Bánh ép Huế là sản phẩm được chế biến theo công thức đặc biệt riêng, nhất là khi kết hợp hài hòa giữa thịt mỡ cùng với hương thơm của sả, hành, ớt, tạo nên vị ngon khó cưỡng, không thể tách rời. Bên cạnh đó, bánh có thể ăn kèm với tương ớt cay cay thì quá là ngon miệng. Bánh không chất bảo quản, không màu thực phẩm và được đóng gói trong hộp giấy đảm bảo chất lượng sản phẩm an toàn, khi được chứng nhận và cung cấp chứng chỉ an toàn vệ sinh thực phẩm HACCP.",
                            ExpiryDate = new DateTime(2025, 1, 25, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9726),
                            Name = "Bánh Ép Huế Gói Snack BBQ Vị Thịt Nướng 40g",
                            Price = 35000m,
                            Quantity = 50,
                            Slug = "banh-ep-hue-goi-snack-bbq-vi-thit-nuong-40g"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 12, 26, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9731),
                            Description = "Bánh ép Huế là một đặc sản khởi nguồn từ biển Thuận An, Huế. Bánh ép Huế là sản phẩm được chế biến theo công thức đặc biệt riêng, nhất là khi kết hợp hài hòa giữa thịt mỡ cùng với hương thơm của sả, hành, ớt, tạo nên vị ngon khó cưỡng, không thể tách rời. Bên cạnh đó, bánh có thể ăn kèm với tương ớt cay cay thì quá là ngon miệng. Bánh không chất bảo quản, không màu thực phẩm và được đóng gói trong hộp giấy đảm bảo chất lượng sản phẩm an toàn, khi được chứng nhận và cung cấp chứng chỉ an toàn vệ sinh thực phẩm HACCP.",
                            ExpiryDate = new DateTime(2025, 1, 25, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9732),
                            Name = "Bánh Ép Huế Hải Sản Vị Tôm Thịt 65G",
                            Price = 50000m,
                            Quantity = 50,
                            Slug = "banh-ep-hue-hai-san-vi-tom-thit-65g"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 12, 26, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9735),
                            Description = "Bánh ép Huế là một đặc sản khởi nguồn từ biển Thuận An, Huế. Bánh ép Huế là sản phẩm được chế biến theo công thức đặc biệt riêng, nhất là khi kết hợp hài hòa giữa thịt mỡ cùng với hương thơm của sả, hành, ớt, tạo nên vị ngon khó cưỡng, không thể tách rời. Bên cạnh đó, bánh có thể ăn kèm với tương ớt cay cay thì quá là ngon miệng. Bánh không chất bảo quản, không màu thực phẩm và được đóng gói trong hộp giấy đảm bảo chất lượng sản phẩm an toàn, khi được chứng nhận và cung cấp chứng chỉ an toàn vệ sinh thực phẩm HACCP.",
                            ExpiryDate = new DateTime(2025, 1, 25, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9735),
                            Name = "Bánh Ép Huế Hải Sản Vị Tôm Thịt 40G",
                            Price = 30000m,
                            Quantity = 50,
                            Slug = "banh-ep-hue-hai-san-vi-tom-thit-40g"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 12, 26, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9738),
                            Description = "Bánh ép Huế là một đặc sản khởi nguồn từ biển Thuận An, Huế. Bánh ép Huế là sản phẩm được chế biến theo công thức đặc biệt riêng, nhất là khi kết hợp hài hòa giữa thịt mỡ cùng với hương thơm của sả, hành, ớt, tạo nên vị ngon khó cưỡng, không thể tách rời. Bên cạnh đó, bánh có thể ăn kèm với tương ớt cay cay thì quá là ngon miệng. Bánh không chất bảo quản, không màu thực phẩm và được đóng gói trong hộp giấy đảm bảo chất lượng sản phẩm an toàn, khi được chứng nhận và cung cấp chứng chỉ an toàn vệ sinh thực phẩm HACCP.",
                            ExpiryDate = new DateTime(2025, 1, 25, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9738),
                            Name = "Bánh ép Huế chay vị Sen Huế 65G",
                            Price = 50000m,
                            Quantity = 50,
                            Slug = "banh-ep-hue-chay-vi-sen-hue-65g"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 12, 26, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9742),
                            Description = "Bánh ép Huế là một đặc sản khởi nguồn từ biển Thuận An, Huế. Bánh ép Huế là sản phẩm được chế biến theo công thức đặc biệt riêng, nhất là khi kết hợp hài hòa giữa thịt mỡ cùng với hương thơm của sả, hành, ớt, tạo nên vị ngon khó cưỡng, không thể tách rời. Bên cạnh đó, bánh có thể ăn kèm với tương ớt cay cay thì quá là ngon miệng. Bánh không chất bảo quản, không màu thực phẩm và được đóng gói trong hộp giấy đảm bảo chất lượng sản phẩm an toàn, khi được chứng nhận và cung cấp chứng chỉ an toàn vệ sinh thực phẩm HACCP.",
                            ExpiryDate = new DateTime(2025, 1, 25, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9743),
                            Name = "Bánh ép Huế chay vị Nấm Hương 65G",
                            Price = 50000m,
                            Quantity = 20,
                            Slug = "banh-ep-hue-chay-vi-nam-huong-65g"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 12, 26, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9746),
                            Description = "Bánh ép Huế là một đặc sản khởi nguồn từ biển Thuận An, Huế. Bánh ép Huế là sản phẩm được chế biến theo công thức đặc biệt riêng, nhất là khi kết hợp hài hòa giữa thịt mỡ cùng với hương thơm của sả, hành, ớt, tạo nên vị ngon khó cưỡng, không thể tách rời. Bên cạnh đó, bánh có thể ăn kèm với tương ớt cay cay thì quá là ngon miệng. Bánh không chất bảo quản, không màu thực phẩm và được đóng gói trong hộp giấy đảm bảo chất lượng sản phẩm an toàn, khi được chứng nhận và cung cấp chứng chỉ an toàn vệ sinh thực phẩm HACCP.",
                            ExpiryDate = new DateTime(2025, 1, 25, 16, 16, 53, 77, DateTimeKind.Local).AddTicks(9746),
                            Name = "Bánh Ép Huế BBQ Vị Thịt Nướng 65G",
                            Price = 50000m,
                            Quantity = 20,
                            Slug = "banh-ep-hue-bbq-vi-thit-nuong-65g"
                        });
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageId = 3,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            ImageId = 4,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            ImageId = 5,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageId = 6,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 7,
                            ImageId = 7,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 8,
                            ImageId = 8,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 9,
                            ImageId = 9,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 10,
                            ImageId = 10,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 11,
                            ImageId = 11,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 12,
                            ImageId = 12,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 13,
                            ImageId = 13,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 14,
                            ImageId = 14,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 15,
                            ImageId = 15,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 16,
                            ImageId = 16,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 17,
                            ImageId = 17,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 18,
                            ImageId = 18,
                            ProductId = 8
                        });
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.Cart", b =>
                {
                    b.HasOne("DP_Shop.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DP_Shop.Data.Entities.ApplicationUser", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.Order", b =>
                {
                    b.HasOne("DP_Shop.Data.Entities.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.OrderProduct", b =>
                {
                    b.HasOne("DP_Shop.Data.Entities.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DP_Shop.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.Product", b =>
                {
                    b.HasOne("DP_Shop.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.ProductImage", b =>
                {
                    b.HasOne("DP_Shop.Data.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DP_Shop.Data.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.UserAddress", b =>
                {
                    b.HasOne("DP_Shop.Data.Entities.Address", "Address")
                        .WithMany("UserAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DP_Shop.Data.Entities.ApplicationUser", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DP_Shop.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DP_Shop.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DP_Shop.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DP_Shop.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.Address", b =>
                {
                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("DP_Shop.Data.Entities.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
